# Generated by Django 5.1.5 on 2025-04-25 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='emotion',
            field=models.CharField(default='neutral', max_length=20),
        ),
        migrations.AddField(
            model_name='history',
            name='response',
            field=models.CharField(default='default_response', max_length=255),
        ),
        migrations.AlterField(
            model_name='history',
            name='query',
            field=models.TextField(),
        ),
    ]
