# Generated by Django 5.1.5 on 2025-04-25 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_history_emotion_history_response_alter_history_query'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='emotion',
        ),
        migrations.RemoveField(
            model_name='history',
            name='response',
        ),
        migrations.AlterField(
            model_name='history',
            name='query',
            field=models.CharField(max_length=255),
        ),
    ]
