# Generated by Django 5.1.5 on 2025-04-25 11:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_journalentry_journal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='user',
        ),
        migrations.AddField(
            model_name='journal',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
