# Generated by Django 5.1.5 on 2025-04-25 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_journal_created_at_remove_journal_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journal',
            old_name='entry',
            new_name='content',
        ),
        migrations.AlterField(
            model_name='journal',
            name='mood',
            field=models.CharField(max_length=50),
        ),
    ]
